### PR TITLE
0.35.0 heb7bd7

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
Looks good to me. I'll merge once the CI completes.

**Comment by jan-janssen** [comment]
```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/flask-smorest_1691943744334/test_tmp/run_test.py", line 2, in <module>
    import flask_smorest
  File "/home/conda/feedstock_root/build_artifacts/flask-smorest_1691943744334/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.11/site-packages/flask_smorest/__init__.py", line 6, in <module>
    from .blueprint import Blueprint  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/flask-smorest_1691943744334/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.11/site-packages/flask_smorest/blueprint.py", line 44, in <module>
    from flask.views import MethodViewType
ImportError: cannot import name 'MethodViewType' from 'flask.views' (/home/conda/feedstock_root/build_artifacts/flask-smorest_1691943744334/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.11/site-packages/flask/views.py)
```

**Comment by jan-janssen** [comment]
@synapticarbors  it is ready now

**Pull request merged**
